// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAME1sIEbI5PA8txeeTWth7dHblFLQ3LLQ',
    appId: '1:662289034816:web:dc93d373841ee2186179a5',
    messagingSenderId: '662289034816',
    projectId: 'truck-tracker-fa0b0',
    authDomain: 'truck-tracker-fa0b0.firebaseapp.com',
    storageBucket: 'truck-tracker-fa0b0.firebasestorage.app',
    measurementId: 'G-ZSXY1N4QSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQTgC7MN69Q2Mp5ugD5t5DCYjNLK2Pqmg',
    appId: '1:662289034816:android:9dd087d36dafa4d46179a5',
    messagingSenderId: '662289034816',
    projectId: 'truck-tracker-fa0b0',
    storageBucket: 'truck-tracker-fa0b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfL61QE0QtDlLaD223eSsuu7rlumaApsk',
    appId: '1:662289034816:ios:b3210b1687ba991a6179a5',
    messagingSenderId: '662289034816',
    projectId: 'truck-tracker-fa0b0',
    storageBucket: 'truck-tracker-fa0b0.firebasestorage.app',
    iosBundleId: 'com.example.truckTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfL61QE0QtDlLaD223eSsuu7rlumaApsk',
    appId: '1:662289034816:ios:b3210b1687ba991a6179a5',
    messagingSenderId: '662289034816',
    projectId: 'truck-tracker-fa0b0',
    storageBucket: 'truck-tracker-fa0b0.firebasestorage.app',
    iosBundleId: 'com.example.truckTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAME1sIEbI5PA8txeeTWth7dHblFLQ3LLQ',
    appId: '1:662289034816:web:0a28d630a92f4d6f6179a5',
    messagingSenderId: '662289034816',
    projectId: 'truck-tracker-fa0b0',
    authDomain: 'truck-tracker-fa0b0.firebaseapp.com',
    storageBucket: 'truck-tracker-fa0b0.firebasestorage.app',
    measurementId: 'G-ZXMGEH24G6',
  );
}
